name: Builder

env:
  BUILD_ARGS: ""

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Building for ARMV7
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm/v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm/v7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ghcr.io/albertogeniola/home-assistant-docker-armv7:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm/v7
          github-token: ${{ secrets.GITHUB_TOKEN }}
