name: Builder

env:
  BUILD_ARGS: ""

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Building for ARMV7
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
      - name: Setup QEMU
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm/v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm/v7
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          outputs: type=docker,dest=/tmp/image.tar
          tags: albertogeniola/home-assistant-docker-armv7:latest
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built_armv7_image
          path: /tmp/image.tar
      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS != '--test'
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push via shell command
        if: env.BUILD_ARGS != '--test'
        run: |
          # docker load --input /tmp/image.tar
          docker push ghcr.io/albertogeniola/home-assistant-docker-armv7:latest
      - name: Push via action
        if: env.BUILD_ARGS != '--test'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: albertogeniola/home-assistant-docker-armv7:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
